const { DataTypes } = require('sequelize');
const { sequelize } = require('../../config/database');
const { BaseAuditedModel } = require('../../core/AuditedModel');

/**
 * BR-12: "Production requirement = Ordered Qty - Available (uncommitted)
 * Qty. A production sheet is proposed, not auto-executed — a human confirms
 * it." PROPOSED plans are generated by production.service.js#generateProposal
 * and can be edited before CONFIRMED; nothing in this table ever creates
 * stock by itself — that only happens via ProductionEntry.
 */
class ProductionPlan extends BaseAuditedModel {}

ProductionPlan.initAudited(
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    factoryId: {
      type: DataTypes.UUID,
      allowNull: false,
    },
    planDate: {
      type: DataTypes.DATEONLY,
      allowNull: false,
    },
    status: {
      type: DataTypes.ENUM('PROPOSED', 'CONFIRMED'),
      allowNull: false,
      defaultValue: 'PROPOSED',
    },
    notes: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
  },
  {
    sequelize,
    tableName: 'production_plans',
  }
);

module.exports = { ProductionPlan };
